begin;

create table if not exists public.dispositivos_cliente (
  id bigint generated by default as identity primary key,
  auth_uid uuid not null unique,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  pessoa_autorizada_id bigint references public.pessoas_autorizadas(id) on delete set null,
  nome_dispositivo text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  ultimo_acesso timestamptz not null default now()
);

alter table public.clientes add column if not exists codigo_acesso_hash text;
alter table public.pessoas_autorizadas add column if not exists codigo_acesso_hash text;
alter table public.dispositivos_cliente enable row level security;

create index if not exists idx_dispositivos_auth on public.dispositivos_cliente(auth_uid);
create index if not exists idx_dispositivos_cliente on public.dispositivos_cliente(cliente_id);

-- Use no SQL Editor enquanto o painel do gerente ainda não existe.
create or replace function public.definir_codigo_cliente(p_telefone text, p_codigo text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if length(trim(p_codigo)) < 4 then raise exception 'O código precisa ter pelo menos 4 caracteres.'; end if;
  update public.clientes set codigo_acesso_hash=crypt(trim(p_codigo), gen_salt('bf')) where telefone=p_telefone;
  if not found then raise exception 'Cliente não encontrado.'; end if;
end; $$;
revoke all on function public.definir_codigo_cliente(text,text) from public, anon, authenticated;

create or replace function public.definir_codigo_autorizado(p_telefone text, p_codigo text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if length(trim(p_codigo)) < 4 then raise exception 'O código precisa ter pelo menos 4 caracteres.'; end if;
  update public.pessoas_autorizadas set codigo_acesso_hash=crypt(trim(p_codigo), gen_salt('bf')) where telefone=p_telefone;
  if not found then raise exception 'Pessoa autorizada não encontrada.'; end if;
end; $$;
revoke all on function public.definir_codigo_autorizado(text,text) from public, anon, authenticated;

-- Vincula o usuário anônimo autenticado do Supabase ao cadastro, após validar telefone + código.
create or replace function public.ativar_aparelho(p_nome text, p_telefone text, p_codigo text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_uid uuid; v_cliente public.clientes%rowtype; v_aut public.pessoas_autorizadas%rowtype;
begin
  v_uid := auth.uid();
  if v_uid is null then raise exception 'Sessão de autenticação inexistente.'; end if;
  if exists(select 1 from public.dispositivos_cliente where auth_uid=v_uid and ativo=true) then
    return jsonb_build_object('ok',true,'ja_ativado',true);
  end if;

  select * into v_cliente from public.clientes where telefone=trim(p_telefone) and ativo=true limit 1;
  if found then
    if v_cliente.codigo_acesso_hash is null or crypt(trim(p_codigo),v_cliente.codigo_acesso_hash)<>v_cliente.codigo_acesso_hash then
      raise exception 'Número ou código de acesso inválido.';
    end if;
    update public.clientes set nome_cliente=coalesce(nullif(trim(p_nome),''),nome_cliente) where id=v_cliente.id;
    insert into public.dispositivos_cliente(auth_uid,cliente_id,nome_dispositivo) values(v_uid,v_cliente.id,'Celular do cliente')
      on conflict(auth_uid) do update set cliente_id=excluded.cliente_id,pessoa_autorizada_id=null,ativo=true,ultimo_acesso=now();
    return jsonb_build_object('ok',true,'cliente_id',v_cliente.id,'nome',coalesce(nullif(trim(p_nome),''),v_cliente.nome_cliente,v_cliente.nome_empresa));
  end if;

  select * into v_aut from public.pessoas_autorizadas where telefone=trim(p_telefone) and ativo=true limit 1;
  if found then
    if v_aut.codigo_acesso_hash is null or crypt(trim(p_codigo),v_aut.codigo_acesso_hash)<>v_aut.codigo_acesso_hash then
      raise exception 'Número ou código de acesso inválido.';
    end if;
    insert into public.dispositivos_cliente(auth_uid,cliente_id,pessoa_autorizada_id,nome_dispositivo)
      values(v_uid,v_aut.cliente_id,v_aut.id,'Celular autorizado')
      on conflict(auth_uid) do update set cliente_id=excluded.cliente_id,pessoa_autorizada_id=excluded.pessoa_autorizada_id,ativo=true,ultimo_acesso=now();
    return jsonb_build_object('ok',true,'cliente_id',v_aut.cliente_id,'pessoa_autorizada_id',v_aut.id,'nome',v_aut.nome);
  end if;

  raise exception 'Número não encontrado. Fale com a Produtos Gilçana.';
end; $$;
grant execute on function public.ativar_aparelho(text,text,text) to authenticated;

create or replace function public.minha_conta()
returns jsonb language sql security definer set search_path='' stable as $$
  select jsonb_build_object(
    'cliente_id',c.id,'nome_empresa',c.nome_empresa,'nome_cliente',c.nome_cliente,'telefone',c.telefone,
    'pessoa_autorizada_id',d.pessoa_autorizada_id,
    'nome_acesso',coalesce(pa.nome,c.nome_cliente,c.nome_empresa),'notificacoes_ativas',c.notificacoes_ativas
  )
  from public.dispositivos_cliente d join public.clientes c on c.id=d.cliente_id
  left join public.pessoas_autorizadas pa on pa.id=d.pessoa_autorizada_id
  where d.auth_uid=auth.uid() and d.ativo=true and c.ativo=true limit 1;
$$;
grant execute on function public.minha_conta() to authenticated;

-- Políticas privadas por aparelho vinculado.
drop policy if exists cliente_le_proprios_pedidos on public.pedidos;
create policy cliente_le_proprios_pedidos on public.pedidos for select to authenticated using (
  exists(select 1 from public.dispositivos_cliente d where d.auth_uid=auth.uid() and d.cliente_id=pedidos.cliente_id and d.ativo=true)
);
drop policy if exists cliente_le_itens_proprios on public.itens_pedido;
create policy cliente_le_itens_proprios on public.itens_pedido for select to authenticated using (
  exists(select 1 from public.pedidos p join public.dispositivos_cliente d on d.cliente_id=p.cliente_id where p.id=itens_pedido.pedido_id and d.auth_uid=auth.uid() and d.ativo=true)
);
drop policy if exists cliente_le_mensagens on public.mensagens;
create policy cliente_le_mensagens on public.mensagens for select to authenticated using (
  exists(select 1 from public.dispositivos_cliente d where d.auth_uid=auth.uid() and d.cliente_id=mensagens.cliente_id and d.ativo=true)
);
drop policy if exists cliente_le_notificacoes on public.notificacoes;
create policy cliente_le_notificacoes on public.notificacoes for select to authenticated using (
  exists(select 1 from public.dispositivos_cliente d where d.auth_uid=auth.uid() and d.cliente_id=notificacoes.cliente_id and d.ativo=true)
);

grant select on public.pedidos, public.itens_pedido, public.mensagens, public.notificacoes to authenticated;

-- Pedido seguro: identidade vem da sessão, nunca do JavaScript.
create or replace function public.criar_meu_pedido(p_data_entrega date,p_itens jsonb)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_d public.dispositivos_cliente%rowtype; v_id bigint;
begin
  select * into v_d from public.dispositivos_cliente where auth_uid=auth.uid() and ativo=true limit 1;
  if not found then raise exception 'Aparelho não autorizado.'; end if;
  v_id := public.criar_pedido(v_d.cliente_id,v_d.pessoa_autorizada_id,p_data_entrega,p_itens);
  return v_id;
end; $$;
grant execute on function public.criar_meu_pedido(date,jsonb) to authenticated;

create or replace function public.enviar_minha_mensagem(p_pedido_id bigint,p_mensagem text)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_d public.dispositivos_cliente%rowtype;
begin
  select * into v_d from public.dispositivos_cliente where auth_uid=auth.uid() and ativo=true limit 1;
  if not found then raise exception 'Aparelho não autorizado.'; end if;
  if p_pedido_id is not null and not exists(select 1 from public.pedidos where id=p_pedido_id and cliente_id=v_d.cliente_id) then raise exception 'Pedido inválido.'; end if;
  return public.enviar_mensagem(v_d.cliente_id,p_pedido_id,'cliente',p_mensagem);
end; $$;
grant execute on function public.enviar_minha_mensagem(bigint,text) to authenticated;

create or replace function public.marcar_minhas_notificacoes_lidas()
returns void language plpgsql security definer set search_path='' as $$
declare v_cliente bigint;
begin
 select cliente_id into v_cliente from public.dispositivos_cliente where auth_uid=auth.uid() and ativo=true limit 1;
 if v_cliente is null then raise exception 'Aparelho não autorizado.'; end if;
 update public.notificacoes set lida=true where cliente_id=v_cliente and lida=false;
end; $$;
grant execute on function public.marcar_minhas_notificacoes_lidas() to authenticated;

commit;
