-- Produtos Gilçana Cliente V3.3
-- Execute UMA VEZ no SQL Editor do MESMO projeto Supabase antes de testar a V3.3.

begin;

-- Galeria opcional de imagens por produto.
create table if not exists public.produto_imagens (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id) on delete cascade,
  imagem_url text not null,
  ordem integer not null default 0,
  criado_em timestamptz not null default now()
);
create index if not exists produto_imagens_produto_idx on public.produto_imagens(produto_id,ordem,id);
alter table public.produto_imagens enable row level security;
drop policy if exists cliente_le_imagens_produto on public.produto_imagens;
create policy cliente_le_imagens_produto on public.produto_imagens for select to authenticated using (
  exists(select 1 from public.produtos p where p.id=produto_imagens.produto_id and p.ativo=true)
);
grant select on public.produto_imagens to authenticated;

-- Reinstala a RPC do chat do cliente (Enter e botão Enviar usam esta função).
create or replace function public.enviar_minha_mensagem(p_pedido_id bigint,p_mensagem text)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_d public.dispositivos_cliente%rowtype; v_texto text;
begin
  select * into v_d from public.dispositivos_cliente where auth_uid=auth.uid() and ativo=true limit 1;
  if not found then raise exception 'Aparelho não autorizado.'; end if;
  v_texto:=trim(coalesce(p_mensagem,''));
  if v_texto='' then raise exception 'A mensagem está vazia.'; end if;
  if p_pedido_id is not null and not exists(select 1 from public.pedidos where id=p_pedido_id and cliente_id=v_d.cliente_id) then
    raise exception 'Pedido inválido.';
  end if;
  return public.enviar_mensagem(v_d.cliente_id,p_pedido_id,'cliente',v_texto);
end; $$;
revoke all on function public.enviar_minha_mensagem(bigint,text) from public,anon;
grant execute on function public.enviar_minha_mensagem(bigint,text) to authenticated;

-- Mensagens automáticas de acompanhamento no chat.
-- O pedido criado recebe a mensagem de recebimento; ao ser confirmado pelo gerente,
-- o cliente recebe a mensagem de que entrou em preparação.
create or replace function public.chat_status_pedido_cliente()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if tg_op='INSERT' then
    perform public.enviar_mensagem(new.cliente_id,new.id,'sistema',
      'Pedido recebido. Recebemos o seu pedido #'||coalesce(new.numero::text,new.id::text)||'.');
  elsif new.status is distinct from old.status then
    if new.status='recebido' then
      perform public.enviar_mensagem(new.cliente_id,new.id,'sistema',
        'Pedido recebido. O seu pedido #'||coalesce(new.numero::text,new.id::text)||' foi recebido.');
    elsif new.status='confirmado' then
      perform public.enviar_mensagem(new.cliente_id,new.id,'sistema',
        'Pedido em preparação. O seu pedido #'||coalesce(new.numero::text,new.id::text)||' foi confirmado e entrou em preparação.');
    elsif new.status='pronto_envio' then
      perform public.enviar_mensagem(new.cliente_id,new.id,'sistema',
        'Pedido pronto para envio. O seu pedido #'||coalesce(new.numero::text,new.id::text)||' está pronto para envio.');
    elsif new.status='cancelado' then
      perform public.enviar_mensagem(new.cliente_id,new.id,'sistema',
        'Pedido cancelado. O pedido #'||coalesce(new.numero::text,new.id::text)||' foi cancelado.');
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists trg_chat_status_pedido_cliente on public.pedidos;
create trigger trg_chat_status_pedido_cliente
after insert or update of status on public.pedidos
for each row execute function public.chat_status_pedido_cliente();

commit;
