-- Produtos Gilçana Cliente V3.13 — dispositivos para Web Push/FCM
begin;
create table if not exists public.push_dispositivos (
 id bigint generated by default as identity primary key,
 cliente_id bigint not null references public.clientes(id) on delete cascade,
 auth_uid uuid not null,
 token text not null unique,
 plataforma text,
 endpoint text,
 ativo boolean not null default true,
 criado_em timestamptz not null default now(),
 atualizado_em timestamptz not null default now()
);
create index if not exists push_dispositivos_cliente_idx on public.push_dispositivos(cliente_id) where ativo=true;
alter table public.push_dispositivos enable row level security;
revoke all on public.push_dispositivos from public,anon,authenticated;

create or replace function public.registrar_meu_push(p_token text,p_plataforma text default null,p_endpoint text default null)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_cliente bigint;
begin
 select cliente_id into v_cliente from public.dispositivos_cliente where auth_uid=auth.uid() and ativo=true limit 1;
 if v_cliente is null then raise exception 'Aparelho não autorizado.'; end if;
 if length(trim(coalesce(p_token,'')))<20 then raise exception 'Token inválido.'; end if;
 insert into public.push_dispositivos(cliente_id,auth_uid,token,plataforma,endpoint,ativo,atualizado_em)
 values(v_cliente,auth.uid(),trim(p_token),left(p_plataforma,500),left(p_endpoint,500),true,now())
 on conflict(token) do update set cliente_id=excluded.cliente_id,auth_uid=excluded.auth_uid,plataforma=excluded.plataforma,endpoint=excluded.endpoint,ativo=true,atualizado_em=now();
 return true;
end;$$;
revoke all on function public.registrar_meu_push(text,text,text) from public,anon;
grant execute on function public.registrar_meu_push(text,text,text) to authenticated;

create or replace function public.desativar_meus_push()
returns boolean language plpgsql security definer set search_path='' as $$
begin
 update public.push_dispositivos set ativo=false,atualizado_em=now() where auth_uid=auth.uid();
 return true;
end;$$;
revoke all on function public.desativar_meus_push() from public,anon;
grant execute on function public.desativar_meus_push() to authenticated;
commit;
